name: Run Tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432/tcp

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.4.6

      - name: Install dependencies
        run: |
          sudo apt-get install libpq-dev
          gem install bundler
          bundle install

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres@localhost:${{ job.services.postgres.ports[5432] }}/
        run: |
          bundle exec rspec
